val duration : string
val status : string
val minor_words : string
val promoted_words : string
val major_words : string
val minor_collections : string
val major_collections : string
val heap_words : string
val heap_chunks : string
val compactions : string
val live_words : string
val live_blocks : string
val free_words : string
val free_blocks : string
val largest_free : string
val fragments : string
val top_heap_words : string
val stack_size : string
